#! /bin/sh

sxhkd &

my_laptop_external_monitor=$(xrandr --query | grep 'VGA1')
if [[ $my_laptop_external_monitor = VGA1\ connected* ]]; then
    xrandr --output LVDS1 --primary --mode 1366x768 --rotate normal --output VGA1 --mode 1360x768 --rotate normal --right-of LVDS1
	bspc monitor LVDS1 -d I II III
	bspc monitor VGA1 -d IV V VI
else
	bspc monitor -d I II III IV V VI
fi

feh --bg-fill ~/Imagens/dracula/arch.png
~/.config/polybar/launch.sh

bspc config border_width         0
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true
bspc config border_radius 		 6

#bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a megasync state=floating

picom &
flameshot &
numlockx on &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
/usr/lib/xfce4/notifyd/xfce4-notifyd
