#! /bin/sh

sxhkd &

my_laptop_external_monitor=$(xrandr --query | grep 'VGA-1')
if [[ $my_laptop_external_monitor = VGA-1\ connected* ]]; then
    xrandr --output LVDS-1 --primary --mode 1366x768 --rotate normal --output VGA-1 --mode 1360x768 --rotate normal --right-of LVDS-1
	bspc monitor LVDS-1 -d I II III
	bspc monitor VGA-1 -d IV V VI
else
	bspc monitor -d I II III IV V VI
fi

feh --bg-fill ~/Imagens/Wallpapers/j7JT3nA.jpg
~/.config/polybar/launch.sh

bspc config border_width         0
bspc config window_gap           5

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true
#bspc config border_radius 		 6

#bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a MEGAsync state=floating
#bspc rule -a discord desktop='^4'
#bspc rule -a TelegramDesktop desktop='^4'

xautolock -detectsleep -time 10 -locker "/home/fhilipe/.config/polybar/scripts/lock.sh" -notify 30 -notifier "notify-send -u critical -t 10000 -- 'LOCKING screen in 30 seconds'" &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
picom &
flameshot &
numlockx on &
dunst &
megasync &
# mailspring &
# insync start &
# telegram-desktop &
# discord &
# kdeconnect-indicator &
