#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

# ##############################################################################
# #                                AUTOSTART APPS                              #
# ##############################################################################

dunst --config $HOME/.config/dunst/dunstrc &
$HOME/.local/bin/eww daemon &
picom --config $HOME/.config/picom/picom.conf &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
xsetroot -cursor_name left_ptr &
xinput set-button-map 14 3 2 1 4 5 6 7 8 9 &
sh $HOME/.config/polybar/launch.sh &
feh --bg-fill ~/Pictures/Wallpapers/pastel/thumbrefeeldtowerz2.png &
xautolock -detectsleep -time 10 -locker "betterlockscreen -l dim" -notify 30 -notifier "notify-send -u critical -t 30 -- 'LOCKING screen in 30 seconds'" &
blueman-applet &
premid &

# ##############################################################################
# #                            GENERAL CONFIGURATION                           #
# ##############################################################################

bspc monitor -d I II III IV V VI VII VIII

bspc config border_width         3
bspc config window_gap           10

bspc config top_padding          37
bspc config bottom_padding       0

bspc config normal_border_color  "#282828"
bspc config active_border_color  "#282828"
bspc config focused_border_color "#282828"

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# ##############################################################################
# #                                 WINDOW RULES                               #
# ##############################################################################

#bpsc rule -a kitty state=floating
bpsc rule -a Google-chrome desktop=^1
bspc rule -a firefox desktop=^1
bspc rule -a org.gnome.Nautilus desktop=^3
bspc rule -a discord desktop=^4
bspc rule -a Code desktop=^2
bspc rule -a spotify desktop=^6

